name: "main job"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  install-connect-iq:
    name: "Install ConnectIQ"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "8"
      - run: |
          curl -L https://developer.garmin.com/downloads/connect-iq/sdk-manager/connectiq-sdk-manager-linux.zip > connectiq.zip
          unzip connectiq.zip
          sudo apt-get install --reinstall libgtk2.0-0
          echo $(pwd)/bin >> $GITHUB_PATH
          echo $PATH
      - run: |
          sdkmanager
