name: "main job"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  install-connect-iq:
    name: "Install ConnectIQ"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L https://developer.garmin.com/downloads/connect-iq/sdk-manager/connectiq-sdk-manager-linux.zip > connectiq.zip
          unzip connectiq.zip
